---
version: '3.8'
services:
  
  run:
    image: tomcat:9.0.62-jdk8-temurin
    ports:
      - "8080:8080"
    depends_on:
      - bld
      - database
    volumes:
      - type: volume
        source: readyapp/app/
        target: /usr/local/tomcat/webapps/  

      - type: bind
        source: ./WebContent/Config.properties
        target: /usr/local/tomcat/ROOT/Config.properties
     
  bld:
    build:   
      context: build/
    volumes:
      - type: volume
        source: readyapp/
        target: /makeapp

  database:
    image: mysql:5.6.51
    restart: always
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db_app
    ports:
      - "3306:3306"

  jmx:
    image: bitnami/jmx-exporter:latest
    ports:
      - 5556:5556
    volumes:
      - type: bind
        source: ./config.yml
        target: /opt/bitnami/jmx-exporter/config.yml

volumes:
  readyapp:
networks:
  default: